name: Tips
main: net.namedfork.bukkit.Tips.Tips
version: 1.0
author: Jesús A. Álvarez
authorEmail: zydeco@namedfork.net
authorUrl: http://namedfork.net
commands:
  tips:
    description: reload tips
    usage: 'Usage: /tips reload'
    permission: tips.reload